apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-hello-world
  template:
    metadata:
      labels:
        app: angular-hello-world
    spec:
      containers:
#        - image: ravr/angular-hello-world:0.0.10-SNAPSHOT
        - image: USERNAME/IMAGE3:TAG
          imagePullPolicy: Always
          name: angular-hello-world
          ports:
            - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: angular-hello-world
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: angular-hello-world
